language: python

sudo: required

services:
  - docker

env:
  global:
    - REPO=wodby/drupal-php
    - secure: J636lOAmg/NiJA6qQ/MmQsxviLBWcVp34+jcmUv0m6VQQ8bkjIuQwqEJwPUIDXkUO15s6eVqLsznKUNzcoCQYz5xvlNAK9v9fOZKOb4v7vrBoQpfTyp5hVwBVIMj2IZmpYVCZFhvh2YTHQoGT+SemYOqMH+ohzffgrDCv9BJpMZ4GOdxAJETXzE6JffW+TI8KoH2kDIGOiVNPalaOyCRCkCEqlz7ubJZHjujus2Ij9+fnIa5JmBKfKf8FuOq34PGYPxT80jFuQ3FQdgYL1laTBwf8Z00vlkc4rA39pUN+POJU1gXCVFZdGpG8LAbX0RuenDiWTGtVzPtha42MZt83NPR49kd40Vi0GD3B0FOFO8YjyRV1lUGhYmD+yf4QBB6MvApUP9Fmx/jZRSUkkGWlTI4vZSqB8PLpNWB8hlSRu3pmoAKmHhtnbnFZUHxNNc385Owhs3HuVCnjdYixQ2yeZrlVcHhQG/UjhpzL5PhktfF45bCo1MNFss4G+GATyJ9XNBT0yEqyJ/IMmxfk/3V9tILK/J8EvAGnhKEX4BRPmmPTrLrMK+1wgZmSuc0r8dLArmloBQqSoRGbOqLBQKt59Cezk2Adq5LiKmJ5HzooMIx85y4rFHZhS216EQ/n2W1LgfYfw6GYmW1y0iqYDU9CgUnV+nU8pBYzXIpOUPdiKM=" # DOCKER_USERNAME
    - secure: tur+tqyzq/yFN4qyUsMjOeFWaNuRX4Qu4h7/GEQCnmUCBpzqJm3YHorocTfdONhifdppj1WrQQemBxm1yBu2j++FCoySvqfziraWfSespkTrATeMU6Fi8WzCFkMAuyngkA5VXls5ed5yskUp3NycqPA5SQW2uYrdFwO2cHZr0/K7vATADvIppapBWd5Jqwqgl+x+oNZ1HTFV/7XYMhj52LgWIDG4XMdV11FvIB5f8yXsn1pyWst53BNS7xhwBxlQHXdsprpPmwVOmOi649XaPWwzTuGoPON28/ORE+un5Gsp7qHMxT7q6Bmk3p9NEKNdHfWId2Q9sCB6pBJiEPVkhWDnw9FZ65DCm00C4M/Ruo2f26I9yv0/aLA4cwEzXWnBikUSYwQtLe1tD6wlgSn+VVyDSal0YPtJbTyKe85vXWVxQkEB00cBvunF1hdCVkDjJQW/mEC3fy8iM+ao1q2vLOzv+HEKmZRhj83K3AjlzRmaNVo2+Xa1JvGL2DHGzctf6zNRJAJ24IGuplcEA7cXBPwpDezX7KojBOXpA8fT7Ilrjgn5uxrrk29tkjPUZou6Y8LKoIKfOPS44qsyKiJ0xOleH/WAw/TbYYZDuOubcpSN5SdXED5zgQ6O39GqP0T1v+3jFRbZaam/fwxloMfBhUw6PKckoE0ZIu3Nr8EE69k=" # DOCKER_PASSWORD
    - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
    - PHP_VER=5.6
    - PHP_VER=7.0

install:
  - docker build -t $REPO:$COMMIT ./$PHP_VER/.
  - docker run -d --name=php $REPO:$COMMIT

script:
  - docker ps | grep -q "$REPO:$COMMIT"
  - docker run --user=82 $REPO:$COMMIT php -v | grep "PHP $PHP_VER"
  - docker run --user=82 $REPO:$COMMIT pwd | grep "/var/www/html"
  - docker run --user=82 $REPO:$COMMIT composer --version
  - docker run --user=82 $REPO:$COMMIT drush version
  - docker run --user=82 $REPO:$COMMIT drupal --version

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - export TAG=`if [ "$BRANCH" == "master" ]; then echo $PHP_VER; else echo $PHP_VER-$BRANCH ; fi`
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag $REPO:$COMMIT $REPO:$PHP_VER-travis-$TRAVIS_BUILD_NUMBER
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - if [ "$BRANCH" == "master" ] && [ "$PHP_VER" == "7.0" ]; then docker tag $REPO:$COMMIT $REPO:latest; fi
  - docker rmi $REPO:$COMMIT
  - docker push $REPO

after_failure:
  - docker logs php
