language: python

sudo: required

services:
  - docker

env:
  global:
    - REPO=wodby/drupal-php
    - COMMIT=${TRAVIS_COMMIT::8}
    - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  matrix:
    - PHP_VER=5.6
    - PHP_VER=7.0

install:
  - mkdir -p /home/travis/.ssh
  - ssh-keygen -t dsa -N '' -f /home/travis/.ssh/testkey
  - chmod 700 /home/travis/.ssh
  - docker build -t $REPO:$COMMIT ./$PHP_VER/.
  - docker run -d -v /home/travis/.ssh:/mnt/ssh --name=php $REPO:$COMMIT

script:
  - docker ps | grep -q "$REPO:$COMMIT"
  - docker exec php php -v | grep "PHP $PHP_VER"
  - docker exec --user=82 php pwd | grep "/var/www/html"
  - docker exec --user=82 php composer --version
  - docker exec --user=82 php drush version
  - docker exec --user=82 php drupal --version
  - docker exec --user=82 php ssh -V
  - docker exec --user=82 php rsync --version
  - docker exec --user=82 php [ -f /home/www-data/.ssh/testkey ]
  - docker exec --user=82 php [ -f /home/www-data/.ssh/testkey.pub ]

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    export TAG=`if [ "$BRANCH" == "master" ]; then echo $PHP_VER; else echo $PHP_VER-$BRANCH ; fi`
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker tag $REPO:$COMMIT $REPO:$PHP_VER-build-$TRAVIS_BUILD_NUMBER
    docker tag $REPO:$COMMIT $REPO:$TAG
    if [ "$BRANCH" == "master" ] && [ "$PHP_VER" == "7.0" ]; then docker tag $REPO:$COMMIT $REPO:latest; fi
    docker rmi $REPO:$COMMIT
    docker push $REPO
  fi

after_failure:
  - docker logs php
