language: python

sudo: required

services:
  - docker

env:
  global:
    - LATEST_PHP_VERSION=7.1
    - DOCKER_VERSION=17.06.2
  matrix:
    - PHP_VER=7.1 PHP_DEBUG=0
    - PHP_VER=7.0 PHP_DEBUG=0
    - PHP_VER=5.6 PHP_DEBUG=0
    - PHP_VER=5.3 PHP_DEBUG=0
    - PHP_VER=7.1 PHP_DEBUG=1
    - PHP_VER=7.0 PHP_DEBUG=1
    - PHP_VER=5.6 PHP_DEBUG=1

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce="${DOCKER_VERSION}~ce-0~ubuntu"

script:
  - cd ./$PHP_VER
  - make && make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make release TAG="$PHP_VER-$TRAVIS_TAG"
    fi

    if [ "$PHP_VER" == "$LATEST_PHP_VERSION" && $PHP_DEBUG != 1 ]; then
      make release TAG=latest
    fi
  fi
