language: python

sudo: required

services:
  - docker

env:
  - TEST_PHP=5.6
  - TEST_PHP=7.0

install:
  - docker build -t php ./$TEST_PHP/.
  - docker run -d php

script:
  - ./scripts/run-tests.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      TAG=$TEST_PHP+$TRAVIS_JOB_NUMBER
      docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      docker tag $DOCKER_PROJECT/$IMAGE_NAME:$TAG $DOCKER_PROJECT/$IMAGE_NAME:latest
      docker push $DOCKER_PROJECT/$IMAGE_NAME:$TAG
    fi

after_failure:
  - docker logs php
