language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=7.1
  matrix:
    - TAG=7.1 PHP_VER=7.1 EXTRA_TAG=7
    - TAG=7.0 PHP_VER=7.0
    - TAG=5.6 PHP_VER=5.6 EXTRA_TAG=5
    - TAG=5.3 PHP_VER=5.3
    - TAG=7.1-dev PHP_VER=7.1 PHP_DEV=1 EXTRA_TAG=7-dev
    - TAG=7.0-dev PHP_VER=7.0 PHP_DEV=1
    - TAG=5.6-dev PHP_VER=5.6 PHP_DEV=1 EXTRA_TAG=5-dev
    - TAG=5.3-dev PHP_VER=5.3 PHP_DEV=1
    - TAG=7.1-dev-macos PHP_VER=7.1 PHP_DEV_MACOS=1 EXTRA_TAG=7-dev-macos
    - TAG=7.0-dev-macos PHP_VER=7.0 PHP_DEV_MACOS=1
    - TAG=5.6-dev-macos PHP_VER=5.6 PHP_DEV_MACOS=1 EXTRA_TAG=5-dev-macos
    - TAG=5.3-dev-macos PHP_VER=5.3 PHP_DEV_MACOS=1

script:
  - cd "${PHP_VER}" || cd "${PHP_VER:0:1}"
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
