name: Build
description: Build Drupal PHP image
inputs:
  version:
    description: php version
    required: true
  dev:
    description: dev version of image
    required: false
  dev_macos:
    description: dev macos version of image
    required: false
  tags:
    description: image tags
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      PHP_VER: ${{ inputs.version }}
      PHP_DEV: ${{ inputs.dev }}
      PHP_DEV_MACOS: ${{ inputs.dev_macos }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
    run: |
      set -e
      make buildx-build
      make test
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
